# Generated by Django 5.0.1 on 2024-02-01 15:16

import simpleForm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleForm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(validators=[simpleForm.models.validate_age]),
        ),
    ]
